/* ============ Billing POS - lang.js (English + Punjabi text) ============ */
const I18N = {
  en: {
    nav_bill: 'Bill', nav_preview: 'Preview', nav_history: 'History', nav_reports: 'Reports', nav_settings: 'Settings',
    newBill: 'New Bill', billNo: 'Bill No.',
    setupTitle: 'Welcome! Set up your shop', setupText: 'Add your shop name, address and UPI ID once. They will appear on every bill.', setupBtn: 'Open Settings',
    quickItems: 'Quick select', itemName: 'Item name', itemPh: 'e.g. Tomato', qty: 'Qty', unit: 'Unit', rate: 'Rate', addItem: 'Add Item',
    items: 'Items', noItems: 'No items yet. Add your first item above.', optional: 'Optional',
    billDetails: 'Bill details', customerName: 'Customer name', customerPhone: 'Customer phone', discount: 'Discount', dateTime: 'Date & time', payMode: 'Payment mode', paidStamp: 'Show "PAID" stamp',
    pay_Cash: 'Cash', pay_UPI: 'UPI', pay_Card: 'Card', pay_Credit: 'Udhaar',
    total: 'Total', itemsCount: 'items', print: 'Print', share: 'Share',
    editItem: 'Edit item', save: 'Save', delete: 'Delete', cancel: 'Cancel', close: 'Close', editBill: 'Edit this bill',
    added: 'Added', removed: 'Removed', undo: 'Undo', billSaved: 'Bill saved, new bill started', settingsSaved: 'Saved ✓',
    enterName: 'Please enter item name', enterQty: 'Please enter quantity', enterRate: 'Please enter rate',
    emptyBill: 'Add at least one item first', shareFail: 'Could not create image. Please try again.', needInternet: 'Open the app once with internet, then try again.',
    making: 'Creating image…', tapToShare: 'Image is ready', deleted: 'Bill deleted', confirmDeleteBill: 'Delete this bill permanently?',
    storageFull: 'App storage is full. Remove the logo, or take a backup and delete old bills.', logoFail: 'Could not read this image', upiInvalid: 'UPI ID looks wrong. Example: 9876543210@ybl',
    searchHistory: 'Search bill no., customer, phone or item', noHistory: 'No bills yet. Your bills will appear here.', noResults: 'No matching bills', current: 'Current',
    p_today: 'Today', p_week: 'This week', p_month: 'This month', p_lastMonth: 'Last month', p_all: 'All time',
    netTotal: 'Total amount', bills: 'Bills', avgBill: 'Average bill', gross: 'Before discount', discountGiven: 'Discount given', byPayment: 'By payment mode', topItems: 'Top items', exportExcel: 'Download for Excel (CSV)', noData: 'No bills in this period',
    shopDetails: 'Shop details', logo: 'Logo', uploadLogo: 'Choose logo', removeLogo: 'Remove', noLogo: 'No logo', shopName: 'Shop name', address1: 'Address line 1', address2: 'Address line 2', phone: 'Phone number',
    billSettings: 'Bill settings', receiptTitle: 'Bill heading', footer: 'Message at bottom', prefix: 'Bill no. prefix', startNo: 'Start bill no. from', paper: 'Printer paper size', upiId: 'UPI ID (for QR code)', upiHint: 'A QR code with the exact amount is printed on bills that are not marked PAID.',
    language: 'Language', savedItems: 'Saved items', noSavedItems: 'Items you add to bills will be remembered here.',
    backup: 'Backup', backupHint: 'All your data is stored only on this phone. Download a backup every week and keep it safe (e.g. in Google Drive).', backupBtn: 'Download backup', restoreBtn: 'Restore backup',
    backupDone: 'Backup downloaded', restoreDone: 'Backup restored', restoreFail: 'This is not a valid backup file', restoreConfirm: 'All current data will be replaced by this backup. Continue?'
  },
  pa: {
    nav_bill: 'ਬਿੱਲ', nav_preview: 'ਪ੍ਰੀਵਿਊ', nav_history: 'ਪੁਰਾਣੇ ਬਿੱਲ', nav_reports: 'ਰਿਪੋਰਟ', nav_settings: 'ਸੈਟਿੰਗਾਂ',
    newBill: 'ਨਵਾਂ ਬਿੱਲ', billNo: 'ਬਿੱਲ ਨੰ.',
    setupTitle: 'ਜੀ ਆਇਆਂ ਨੂੰ! ਆਪਣੀ ਦੁਕਾਨ ਸੈੱਟ ਕਰੋ', setupText: 'ਦੁਕਾਨ ਦਾ ਨਾਮ, ਪਤਾ ਅਤੇ UPI ID ਇੱਕ ਵਾਰ ਭਰੋ। ਇਹ ਹਰ ਬਿੱਲ ਤੇ ਆਪਣੇ ਆਪ ਆਉਣਗੇ।', setupBtn: 'ਸੈਟਿੰਗਾਂ ਖੋਲ੍ਹੋ',
    quickItems: 'ਜਲਦੀ ਚੁਣੋ', itemName: 'ਸਮਾਨ ਦਾ ਨਾਮ', itemPh: 'ਜਿਵੇਂ ਟਮਾਟਰ', qty: 'ਮਾਤਰਾ', unit: 'ਯੂਨਿਟ', rate: 'ਰੇਟ', addItem: 'ਸਮਾਨ ਜੋੜੋ',
    items: 'ਸਮਾਨ', noItems: 'ਹਾਲੇ ਕੋਈ ਸਮਾਨ ਨਹੀਂ। ਉੱਪਰੋਂ ਪਹਿਲਾ ਸਮਾਨ ਜੋੜੋ।', optional: 'ਜ਼ਰੂਰੀ ਨਹੀਂ',
    billDetails: 'ਬਿੱਲ ਦੀ ਜਾਣਕਾਰੀ', customerName: 'ਗਾਹਕ ਦਾ ਨਾਮ', customerPhone: 'ਗਾਹਕ ਦਾ ਫ਼ੋਨ', discount: 'ਛੋਟ', dateTime: 'ਮਿਤੀ ਅਤੇ ਸਮਾਂ', payMode: 'ਭੁਗਤਾਨ ਕਿਵੇਂ ਹੋਇਆ', paidStamp: '"PAID" ਮੋਹਰ ਲਗਾਓ',
    pay_Cash: 'ਨਕਦ', pay_UPI: 'UPI', pay_Card: 'ਕਾਰਡ', pay_Credit: 'ਉਧਾਰ',
    total: 'ਕੁੱਲ', itemsCount: 'ਸਮਾਨ', print: 'ਪ੍ਰਿੰਟ', share: 'ਸ਼ੇਅਰ',
    editItem: 'ਸਮਾਨ ਬਦਲੋ', save: 'ਸੇਵ ਕਰੋ', delete: 'ਮਿਟਾਓ', cancel: 'ਰੱਦ ਕਰੋ', close: 'ਬੰਦ ਕਰੋ', editBill: 'ਇਹ ਬਿੱਲ ਬਦਲੋ',
    added: 'ਜੁੜ ਗਿਆ', removed: 'ਹਟਾ ਦਿੱਤਾ', undo: 'ਵਾਪਸ', billSaved: 'ਬਿੱਲ ਸੇਵ ਹੋ ਗਿਆ, ਨਵਾਂ ਬਿੱਲ ਸ਼ੁਰੂ', settingsSaved: 'ਸੇਵ ਹੋ ਗਿਆ ✓',
    enterName: 'ਸਮਾਨ ਦਾ ਨਾਮ ਲਿਖੋ', enterQty: 'ਮਾਤਰਾ ਲਿਖੋ', enterRate: 'ਰੇਟ ਲਿਖੋ',
    emptyBill: 'ਪਹਿਲਾਂ ਘੱਟੋ-ਘੱਟ ਇੱਕ ਸਮਾਨ ਜੋੜੋ', shareFail: 'ਫ਼ੋਟੋ ਨਹੀਂ ਬਣ ਸਕੀ, ਦੁਬਾਰਾ ਕੋਸ਼ਿਸ਼ ਕਰੋ', needInternet: 'ਇੱਕ ਵਾਰ ਇੰਟਰਨੈੱਟ ਨਾਲ ਐਪ ਖੋਲ੍ਹੋ, ਫਿਰ ਕੋਸ਼ਿਸ਼ ਕਰੋ',
    making: 'ਫ਼ੋਟੋ ਬਣ ਰਹੀ ਹੈ…', tapToShare: 'ਫ਼ੋਟੋ ਤਿਆਰ ਹੈ', deleted: 'ਬਿੱਲ ਮਿਟਾ ਦਿੱਤਾ', confirmDeleteBill: 'ਕੀ ਇਹ ਬਿੱਲ ਹਮੇਸ਼ਾ ਲਈ ਮਿਟਾਉਣਾ ਹੈ?',
    storageFull: 'ਐਪ ਦੀ ਥਾਂ ਭਰ ਗਈ ਹੈ। ਲੋਗੋ ਹਟਾਓ ਜਾਂ ਬੈਕਅੱਪ ਲੈ ਕੇ ਪੁਰਾਣੇ ਬਿੱਲ ਮਿਟਾਓ।', logoFail: 'ਇਹ ਫ਼ੋਟੋ ਨਹੀਂ ਪੜ੍ਹੀ ਜਾ ਸਕੀ', upiInvalid: 'UPI ID ਗਲਤ ਲੱਗਦੀ ਹੈ। ਜਿਵੇਂ: 9876543210@ybl',
    searchHistory: 'ਬਿੱਲ ਨੰਬਰ, ਗਾਹਕ, ਫ਼ੋਨ ਜਾਂ ਸਮਾਨ ਲੱਭੋ', noHistory: 'ਹਾਲੇ ਕੋਈ ਬਿੱਲ ਨਹੀਂ। ਤੁਹਾਡੇ ਬਿੱਲ ਇੱਥੇ ਆਉਣਗੇ।', noResults: 'ਕੋਈ ਬਿੱਲ ਨਹੀਂ ਮਿਲਿਆ', current: 'ਚੱਲ ਰਿਹਾ',
    p_today: 'ਅੱਜ', p_week: 'ਇਹ ਹਫ਼ਤਾ', p_month: 'ਇਹ ਮਹੀਨਾ', p_lastMonth: 'ਪਿਛਲਾ ਮਹੀਨਾ', p_all: 'ਸਾਰੇ',
    netTotal: 'ਕੁੱਲ ਰਕਮ', bills: 'ਬਿੱਲ', avgBill: 'ਔਸਤ ਬਿੱਲ', gross: 'ਛੋਟ ਤੋਂ ਪਹਿਲਾਂ', discountGiven: 'ਦਿੱਤੀ ਛੋਟ', byPayment: 'ਭੁਗਤਾਨ ਅਨੁਸਾਰ', topItems: 'ਸਭ ਤੋਂ ਵੱਧ ਰਕਮ ਵਾਲਾ ਸਮਾਨ', exportExcel: 'Excel ਲਈ ਡਾਊਨਲੋਡ (CSV)', noData: 'ਇਸ ਸਮੇਂ ਵਿੱਚ ਕੋਈ ਬਿੱਲ ਨਹੀਂ',
    shopDetails: 'ਦੁਕਾਨ ਦੀ ਜਾਣਕਾਰੀ', logo: 'ਲੋਗੋ', uploadLogo: 'ਲੋਗੋ ਚੁਣੋ', removeLogo: 'ਹਟਾਓ', noLogo: 'ਲੋਗੋ ਨਹੀਂ', shopName: 'ਦੁਕਾਨ ਦਾ ਨਾਮ', address1: 'ਪਤਾ (ਲਾਈਨ 1)', address2: 'ਪਤਾ (ਲਾਈਨ 2)', phone: 'ਫ਼ੋਨ ਨੰਬਰ',
    billSettings: 'ਬਿੱਲ ਸੈਟਿੰਗਾਂ', receiptTitle: 'ਬਿੱਲ ਦਾ ਸਿਰਲੇਖ', footer: 'ਥੱਲੇ ਵਾਲਾ ਸੁਨੇਹਾ', prefix: 'ਬਿੱਲ ਨੰ. ਤੋਂ ਪਹਿਲਾਂ', startNo: 'ਬਿੱਲ ਨੰ. ਇੱਥੋਂ ਸ਼ੁਰੂ', paper: 'ਪ੍ਰਿੰਟਰ ਕਾਗਜ਼ ਸਾਈਜ਼', upiId: 'UPI ID (QR ਕੋਡ ਲਈ)', upiHint: 'ਜਿਨ੍ਹਾਂ ਬਿੱਲਾਂ ਤੇ PAID ਮੋਹਰ ਨਹੀਂ, ਉਹਨਾਂ ਤੇ ਪੂਰੀ ਰਕਮ ਵਾਲਾ QR ਕੋਡ ਛਪੇਗਾ।',
    language: 'ਭਾਸ਼ਾ', savedItems: 'ਯਾਦ ਰੱਖਿਆ ਸਮਾਨ', noSavedItems: 'ਜੋ ਸਮਾਨ ਤੁਸੀਂ ਬਿੱਲ ਵਿੱਚ ਜੋੜੋਗੇ, ਉਹ ਇੱਥੇ ਯਾਦ ਰਹੇਗਾ।',
    backup: 'ਬੈਕਅੱਪ', backupHint: 'ਤੁਹਾਡਾ ਸਾਰਾ ਡਾਟਾ ਸਿਰਫ਼ ਇਸ ਫ਼ੋਨ ਵਿੱਚ ਹੈ। ਹਰ ਹਫ਼ਤੇ ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ ਕਰਕੇ ਸੰਭਾਲ ਕੇ ਰੱਖੋ (ਜਿਵੇਂ Google Drive ਵਿੱਚ)।', backupBtn: 'ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ', restoreBtn: 'ਬੈਕਅੱਪ ਵਾਪਸ ਲਿਆਓ',
    backupDone: 'ਬੈਕਅੱਪ ਡਾਊਨਲੋਡ ਹੋ ਗਿਆ', restoreDone: 'ਬੈਕਅੱਪ ਵਾਪਸ ਆ ਗਿਆ', restoreFail: 'ਇਹ ਸਹੀ ਬੈਕਅੱਪ ਫ਼ਾਈਲ ਨਹੀਂ', restoreConfirm: 'ਮੌਜੂਦਾ ਸਾਰਾ ਡਾਟਾ ਇਸ ਬੈਕਅੱਪ ਨਾਲ ਬਦਲ ਜਾਵੇਗਾ। ਜਾਰੀ ਰੱਖਣਾ ਹੈ?'
  }
};
